all: my-cat.c
	gcc -o my-cat my-cat.c -Wall -Werror

sed: my-sed.c
	gcc -o my-sed my-sed.c -Wall -Werror

uniq: my-uniq.c
	gcc -o my-uniq my-uniq.c -Wall -Werror

test: test.c
	gcc -o test test.c -Wall -Werror
